# TODO: Way to auth read and write request for specific user+sandbox — system for generating signed upload urls?
# TODO: Append
# TODO: Add defaults
# TODO: Basic auth also

openapi: 3.0.0
info:
  title: envd
  version: 0.1.0
  description: API for managing files content and controlling the envd

servers:
  - url: /v1

paths:
  /sync:
    post:
      summary: Ensure the time and metadata is synced with the host
      responses:
        204:
          description: The time and metadata is synced with the host
        500:
          $ref: "#/components/responses/InternalServerError"

  /health:
    get:
      summary: Check the health of the envd
      responses:
        204:
          description: The envd is healthy
        500:
          $ref: "#/components/responses/InternalServerError"

  /files:
    get:
      summary: Download a file or a specific byte range
      parameters:
        - $ref: "#/components/parameters/FilePath"
        - $ref: "#/components/parameters/Range"
      responses:
        200:
          $ref: "#/components/responses/DownloadSuccess"
        206:
          $ref: "#/components/responses/RangeDownloadSuccess"
        400:
          $ref: "#/components/responses/DirectoryPathError"
        416:
          $ref: "#/components/responses/RangeNotSatisfiableError"
    put:
      summary: Upload a file or a specific byte range
      parameters:
        - $ref: "#/components/parameters/FilePath"
        - $ref: "#/components/parameters/Range"
        - $ref: "#/components/parameters/User"
        - $ref: "#/components/parameters/Mode"
        - $ref: "#/components/parameters/Overwrite"
      requestBody:
        $ref: "#/components/requestBodies/File"
      responses:
        200:
          $ref: "#/components/responses/ExistingFileUploadSuccess"
        201:
          $ref: "#/components/responses/NewFileUploadSuccess"
        409:
          $ref: "#/components/responses/ConflictError"
        400:
          $ref: "#/components/responses/DirectoryPathError"
        416:
          $ref: "#/components/responses/RangeNotSatisfiableError"

components:
  parameters:
    Location:
      name: Location
      in: header
      description: The URL of the uploaded file
      schema:
        type: string
        format: uri
    ContentRange:
      name: Content-Range
      in: header
      description: The range of bytes returned up
      schema:
        type: string
        pattern: '^bytes=\d*-\d*(,\d*-\d*)*|bytes \d*-\d*/\d+$'
    FilePath:
      name: path
      in: path
      required: true
      allowEmptyValue: false
      description: Absolute path to the file, URL encoded.
      schema:
        type: string
    Range:
      name: Range
      in: header
      required: false
      description: Byte range for downloading or uploading a file, formatted as "bytes=start-end" for downloads and "bytes=start-end/total" for uploads.
      schema:
        type: string
        pattern: '^bytes=\d*-\d*(,\d*-\d*)*|bytes \d*-\d*/\d+$'
    User:
      name: User
      in: header
      required: false
      description: User owning the file
      schema:
        type: string
    Mode:
      name: Mode
      in: header
      required: false
      description: File permissions in octal format (e.g., 0755)
      schema:
        type: string
        pattern: "^[0-7]{3,4}$"
    Overwrite:
      name: overwrite
      in: header
      required: false
      description: Overwrite the file if it exists
      schema:
        type: boolean
        default: true

  requestBodies:
    File:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              file:
                type: string
                format: binary

  responses:
    ExistingFileUploadSuccess:
      description: The file was updated successfully.
      headers:
        Content-Range:
          required: false
          $ref: "#/components/parameters/ContentRange"
    NewFileUploadSuccess:
      description: The file was created successfully.
      headers:
        Location:
          $ref: "#/components/parameters/Location"
        Content-Range:
          required: false
          $ref: "#/components/parameters/ContentRange"
    DownloadSuccess:
      description: Entire file downloaded successfully.
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
            description: The file content
    RangeDownloadSuccess:
      description: Specified byte range(s) of the file downloaded successfully.
      headers:
        Content-Range:
          required: true
          $ref: "#/components/parameters/ContentRange"
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
            description: The file content
    DirectoryPathError:
      description: Bad Request - The specified path is a directory. Only files can be downloaded.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    RangeNotSatisfiableError:
      description: Requested Range Not Satisfiable - The specified byte range is outside the size of the file, or the Range header is formatted incorrectly.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    ConflictError:
      description: Conflict - The file already exists and overwrite is false.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Error message
        code:
          type: integer
          description: Error code
