[tool.poetry]
name = "codegen"
version = "0.1.0"
description = ""
authors = ["Devbook <hello@usedevbook.com>"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
gunicorn = "^20.1.0"
langchain = "^0.0.117"
supabase = "^1.0.2"
flask-cors = "^3.0.10"
python-dateutil = "^2.8.2"
urllib3 = "^1.26.14"
pydantic = "^1.10.6"
aenum = "^3.1.11"
python-dotenv = "^1.0.0"
openai = "^0.27.0"
pytest = "^7.2.2"
lxml = "^4.9.2"
flask = "^2.2.3"
asyncio = "^3.4.3"
postgrest-py = "^0.10.6"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
