[tool.poetry]
name = "api-service"
version = "0.1.0"
description = ""
authors = ["Vasek Mlejnsky <vasek.mlejnsky@gmail.com>"]
packages = [{ include = "api_service" }]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
simplejson = "^3.18.3"
python-dotenv = "^1.0.0"
flask = "^2.2.3"
gunicorn = "^20.1.0"
openai = "^0.27.0"
langchain = "^0.0.102"
supabase = "^1.0.1"


[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
