[tool.poetry]
name = "codegen"
version = "0.1.0"
description = ""
authors = ["Devbook <hello@usedevbook.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
langchain = "^0.0.132"
python-dateutil = "^2.8.2"
urllib3 = "^1.26.14"
pydantic = "^1.10.6"
aenum = "^3.1.11"
python-dotenv = "^1.0.0"
openai = "^0.27.0"
lxml = "^4.9.2"
asyncio = "^3.4.3"
postgrest = "^0.10.6"
quart = "^0.18.3"
quart-cors = "^0.6.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pylint = "^2.17.2"
pytest = "^7.2.2"

[tool.poetry.group.deploy]
optional = true

[tool.poetry.group.deploy.dependencies]
gunicorn = "^20.1.0"
uvicorn = {extras = ["standard"], version = "^0.21.1"}

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
