# This wrangler file will be injected withl values during runtime and saved as wrangler.toml

name = "meteo"
main = "./index.js"
# route = ''
compatibility_date = "2022-05-03"
send_metrics = false
node_compat = true

[vars]
SLACK_BOT_ACCESS_TOKEN = "xoxb-625989678439-4949424452337-fLgQoJFqYBYyzOeoRfZ1WMrj"

