name: Build and deploy API

on:
  push:
    paths:
      - 'api-service/**'
    branches:
      - production

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  IMAGE_TAG: us-central1-docker.pkg.dev/${{ secrets.GCE_PROJECT }}/services/e2b-api:latest

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Service Account
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./api-service
          push: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha,scope=e2b-api
          cache-to: type=gha,scope=e2b-api

      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: e2b-api
          image: ${{ env.IMAGE_TAG }}
