name: Generate SDK API references

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  is_new_api_ref:
    name: Is new API reference?
    runs-on: ubuntu-latest
    outputs:
      new_api_ref: ${{ steps.sdk-changes.outputs.new_api_ref }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Check if SDK changes
        id: sdk-changes
        run: |
          IS_NEW_API_REF=$(./.github/scripts/is_new_api_ref.sh)
          echo "new_api_ref=$IS_NEW_API_REF" >> "$GITHUB_OUTPUT"

  sdk-changes:
    name: SDK changes
    needs: [is_new_api_ref]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 9.5

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Configure pnpm
        run: |
          pnpm config set auto-install-peers true
          pnpm config set exclude-links-from-lockfile true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        working-directory: ./packages/python-sdk
        run: poetry install --no-interaction --no-root

      - name: Generate Python SDK API reference
        id: python-sdk-api-ref
        working-directory: ./packages/python-sdk
        run: |
          source .venv/bin/activate
          ./scripts/generate_api_ref.sh

      - name: Generate JS SDK API reference
        id: js-sdk-api-ref
        working-directory: packages/js-sdk
        run: ./scripts/generate_api_ref.sh

      - name: Generate CLI API reference
        id: cli-api-ref
        working-directory: packages/cli
        run: ./scripts/generate_api_ref.sh

      - name: Show docs file structure
        run: tree apps/web/src/app/\(docs\)/docs/api-reference

      - name: Commit new SDK API reference versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/web/src/app/\(docs\)/docs/api-reference
          git commit -m "[skip ci] Release new SDK API reference doc versions" || exit 0
          git push